### ISSUE TITLE
Status

### ISSUE THREAD

**Issue by aksel** [jonas-lundqvist/vlc-spotify#2]
Hi! I know it's like 4 years later, but just wanted to ask, do you have any plans on picking this back up?

Their desktop application is just so bloated. I just want to stream music without it using up most of my RAM and CPU. ;~)

**Comment by jonas-lundqvist** [comment]
Hi @aksel 
Unfortunately the libspotify project seems to dead and forgotten over at Spotify and the talks about the release of a new library seems to just have been hot air. Even if I wanted to resurrect this project I couldn't :/

**Comment by aksel** [comment]
Thanks for the response! :smile: 

Since posting, I have found [spotifyd](https://github.com/Spotifyd/spotifyd), which uses [librespot](https://github.com/librespot-org/librespot/). Solves my issues, pretty much.
